# Generated by Django 3.0.3 on 2020-02-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F1',
        ),
    ]
