# Generated by Django 3.0.3 on 2020-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0003_f1'),
    ]

    operations = [
        migrations.CreateModel(
            name='F2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('block', models.CharField(blank=True, max_length=25, null=True)),
                ('wasting', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stunting', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('underweight', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lbw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'f2',
                'managed': False,
            },
        ),
    ]
